### ISSUE TITLE
Some minor runtime errors

### ISSUE THREAD

**Issue by roysubhankar** [fcdl94/WILSON#1]
Ciao Fabio,

Great work as always, and thanks for sharing your code. :)

I tried to run your code and there appears to be some undeclared arguments such as opts.saliency and opts.l_sal. I removed them and the code runs now. If you could please clarify if they were just typos or you used some form of saliency loss by using the saliency maps?

Thanks.

**Comment by fcdl94** [comment]
Ciao Roy!

Actually, I was still cleaning the code and I forgot to remove them. If you pull the code now, it should be fixed.
They were part of some old experiments but they are not used anymore.

Thanks for your interest :)
