### ISSUE TITLE
How to calculate MIoU

### ISSUE THREAD

**Issue by Chongjie-Si** [fcdl94/WILSON#11]
Hi Fabio,
I wonder how to compute the MIoU in your paper.
Does 1-15 mean only calculating the average of 15 classes, and 16-20 mean the average of another 5 classes, and "all" mean that of total classes (including background)?
Specifically, I want to know whether you included the IoU of the background when it comes to 16-20 and all.

**Comment by fcdl94** [comment]
Hi! 
No, I did not included the background in 16-20 while it is included in the 'all'. Please, refer to Issue #2

**Comment by Chongjie-Si** [comment]
Thanks！
