### ISSUE TITLE
Problems about voc 10-10

### ISSUE THREAD

**Issue by adaxidedakaonang** [fcdl94/WILSON#13]
Thanks for your great project again! Recently I'm trying to reproduce voc 10-10, but the performance of **step 0** model always stop at 58%. However I tried task offline and 15-5, the reproduced results were satisfactory (65% for 15-5 and 76% for offline). Seems only 10-10 is hard to improve, which is very strange. I also use 'MIB' trained step 0 model to train step 1  of 10-10, and I got a worse result (mIoU is 40%). Now I'm really a little bit confused, I follow the same setting with paper:
```
python -u -m torch.distributed.launch --nproc_per_node=1 run.py --num_workers 1  --name Base --step 0 --lr 0.01 --bce --dataset voc --task 10-10 --batch_size 24 --epochs 30 --val_interval 2
```
I wonder if you can give me any advice, I really don't know how to solve it... This is too strange

**Comment by fcdl94** [comment]
Hey, @adaxidedakaonang!

Sorry, I really missed this issue! Did you solve the issue? What was the problem?

**Comment by adaxidedakaonang** [comment]
Ummmmmm... Actually, I didn't solve the problem. But when I transferred to a new machine (cuda12, pytorch2.1, GPU rtx4090), it disappeared. 

The problem was when I ran code with setting pytorch1.8.1, cuda11.1, I got a very bad reproduced result **only** under 10-10. But now for the pytorch2.1 and cuda 12.1, it works very well.

**Comment by fcdl94** [comment]
Nice, thanks for sharing!
