### ISSUE TITLE
not return in transform.py

### ISSUE THREAD

**Issue by wendyhuang2021** [fcdl94/WILSON#15]
Hi! I have little question about `dataset > transform.py`. 
In [line 89](https://github.com/fcdl94/WILSON/blob/41c7d5b21b627722311d559ad5f6d835917f95d1/dataset/transform.py#L89):
```
class Resize(object):
    ...
    def __call__(self, img, lbl=None):
        if lbl is not None:
            if isinstance(lbl, torch.Tensor):
                F.resize(img, self.size, self.interpolation), F.resize(lbl, self.size, InterpolationMode.BILINEAR)# no return
```
Is there missing `return`?

**Comment by fcdl94** [comment]
Yes you're right! Anyway, I'd suggest you to use the PIL Images instead of torch tensors as labels, since it wasn't tested during the experiments (we used PIL Images).

**Comment by wendyhuang2021** [comment]
Thank you for your reply!
