### ISSUE TITLE
Clarification on evaluation metric M-IoU

### ISSUE THREAD

**Issue by roysubhankar** [fcdl94/WILSON#2]
Hi Fabio,

I would like to ask how do you compute the final M-IoU in the tables. In the table below I see that to compute the **Old** and **All** M-IoU for WILSON you do the following:

![Screenshot 2022-04-11 at 10 26 39](https://user-images.githubusercontent.com/42292050/162696769-d785281a-d985-4174-84e3-c42de6e1a64b.png)

1. To compute **Old** you take a mean of the old classes (**excluding** the background class)
2. To compute **All** you take a mean of all the classes (**including** the background class)

If I recall well, in your previous work MiB you said somewhere that you do not take into account the background classes while computing the final metric as bkg is not a class of interest. However, in this work you consider the bkg class to compute the **All** M-IoU. Could you please clarify which calculation should be adopted?

**Comment by fcdl94** [comment]
Ciao @roysubhankar,

Sorry for the late answer. Actually, I started using the background class after the last Continual SemSeg papers, that are using the background for the All class. However, the results are in line, but nearly 1 point less when excluding the background.

Thanks for opening the issue, I should clarifty it better.
