### ISSUE TITLE
COCO-to-VOC Dataset

### ISSUE THREAD

**Issue by novatt** [fcdl94/WILSON#6]
Hi Fabio,
I would like to ask some questions regarding the COCO-to-VOC dataset.
How do the classes names and labels of COCO-to-VOC dataset correspond?
1. Do the **1-60** keep the origin order of the remaining classes after removing all the ones in PASCAL VOC ？
(**ie 1: truck, 2: traffic light, ..., 60: toothbrush**)
2. Do **61-80** correspond to the 1-20 in PASCAL VOC ？
(**ie 61: airplane, 62: bicycle, ..., 80: tv**)

If I understand incorrectly, could you tell me the correct corresponding order？
Thanks!

**Comment by fcdl94** [comment]
You can find here the class ordering: https://github.com/fcdl94/WILSON/blob/41c7d5b21b627722311d559ad5f6d835917f95d1/tasks.py#L3 ?
In 'data' you can also find the script to convert Voc to the coco format

**Comment by novatt** [comment]
I have solved this problem with your help.
Thanks for your quick reply.
