### ISSUE TITLE
Clarification for disjoint VOC splits

### ISSUE THREAD

**Issue by tyler-hayes** [fcdl94/WILSON#7]
Hi Fabio, thanks for the interesting work!

I had a quick question about the disjoint VOC splits: 

Do the indices in `/WILSON/data/voc/10-10/train-0.npy` pertain to the indicies of the filenames from the following list (`file_names`):

```
split_f = '/WILSON/data/voc/splits/train_aug.txt'
with open(os.path.join(split_f), "r") as f:
    file_names = [x[:-1].split(' ') for x in f.readlines()]
file_names = [fn[0].split('/')[-1] for fn in file_names]
```

For example, the 0-th index in `/WILSON/data/voc/10-10/train-0.npy` is `3`, which would correspond with `file_names[3]=/JPEGImages/2007_000068.jpg` from `train_aug.txt`

Thank you in advance for your clarifications!

**Comment by fcdl94** [comment]
Hi Tyler! 

Yes, it is the index relative to the corresponding train_aug file!

**Comment by tyler-hayes** [comment]
Great, thank you for the clarification and quick reply!
