### ISSUE TITLE
Pretrained Weight

### ISSUE THREAD

**Issue by dnwjddl** [fcdl94/WILSON#8]
Hello, 
First of all, thanks for sharing such wonderful work!

I noticed that the pretrained weights currently available are not correct.
Would it be possible to share the correct pretrained weights(`pretrained/resnet101_iabn_sync.pth.tar` )? 

Thank you!

**Comment by fcdl94** [comment]
Hello. 
What do you mean by "not correct"? 
We used the weights from https://github.com/mapillary/inplace_abn . Are you able to use these weights?

**Comment by dnwjddl** [comment]
Hi, Thank you for the comment :) I solved the problem that I previously asked about. 
Additionally, I tried to reproduce the code using the weights of **ResNet101v1 and InPlace-ABN sync** from that website, but the values are coming out lower than expected. 
I'm wondering if there might be any changed parameters or if I accidentally used different weights?

**Comment by fcdl94** [comment]
We used the weights from their repository, without changes. Can you detail what you are obtaining? What method are you reproducing? On which setting?
